### ISSUE TITLE
Is anyone experiencing problems with inputs being cutoff?

### ISSUE THREAD

**Issue by craldaz** [chrislemke/ChatFred#90] opened 2023-08-04 21:52 UTC
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [ X] Yes
- [ ] No

**Describe your problem**
When I write in the Alfred chat box using `cf` I am consistently having my message cutoff before the end and chatgpt is confused. It seems to be an issue related to chatfred catching up to the input, like its interpreting the input on the fly. 

This is particularly problematic when I try to paste text into the chatfred chat box. 

**To Reproduce**
Try to paste text into chatfred chat box. (This also happens with regular inputs if you type fast). 

**Screenshots**
![Screenshot 2023-08-04 at 2 39 07 PM](https://github.com/chrislemke/ChatFred/assets/19959249/e1dcebdb-bb37-4837-8c80-78ef719a96d4)

It seems to be more of a problem since I switched to gpt-4.

**Comment by chrislemke** [comment] 2023-08-12 15:54
Hey @craldaz!
Any news on this? Unfortunately, I was not able to reproduce it.

**Comment by chrislemke** [comment] 2023-08-24 14:54
Thanks for the update. I will close this issue. Feel free to open it up again.

**Closed by chrislemke** 2023-08-24 14:54 UTC
Labels: help wanted
